# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: brew_cellar
      - run:
          name: brew
          command: ./scripts/prepare.sh
          no_output_timeout: 1.5h
      - save_cache:
          key: brew_cellar
          paths:
            - /usr/local/Cellar
      - run:
          name: deploy
          command: ./scripts/deploy.sh
          no_output_timeout: 1.5h

