#https://circleci.com/docs/2.0/
#https://circleci.com/docs/2.0/testing-ios/

version: 2
jobs:
  test:
    macos:
      xcode: "9.0.1"
    steps:
      - name: commands
        command: |
          ./scripts/prepare.sh
          ./scripts/deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test