#https://circleci.com/docs/2.0/
#https://circleci.com/docs/2.0/testing-ios/

version: 2
jobs:
  test:
    macos:
      xcode: "9.0.1"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: ./scripts/prepare.sh
        no_output_timout: 1h
      - save_cache:
          key: dependency-cache
          paths:
            - /usr/local/Cellar
      - run: ./scripts/deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test